submaps:
  - id: A
    boundaries:
      - [[3,8],[3,3]]
      - [[8,8],[1,3]]
      - [[3,8],[1,1]]
      - [[3,3],[1,3]]
    type: "roadway"

  - id: B
    boundaries:
      - [[8, 8], [1, 3]]
      - [[8, 10], [1, 1]]
      - [[10, 10], [1, 3]]
      - [[8, 10], [3, 3]]
    type: "intersection"

  # - id: C
  #   boundaries:
  #     - [[8,10],[3,3]]
  #     - [[8,8],[3,8]]
  #     - [[8,10],[8,8]]
  #     - [[10,10],[3,8]]
  #   type: "roadway"

  - id: D
    boundaries:
      - [[8, 8], [8, 10]]
      - [[8, 10], [8, 8]]
      - [[10, 10], [8, 10]]
      - [[8, 10], [10, 10]]
    type: 'intersection'

  - id: E
    boundaries:
      - [[3,8],[10,10]]
      - [[8,8],[8,10]]
      - [[3,8],[8,8]]
      - [[3,3],[8,10]]
    type: "roadway"

  - id: F
    boundaries:
      - [[1, 1], [8, 10]]
      - [[1, 3], [8, 8]]
      - [[3, 3], [8, 10]]
      - [[1, 3], [10, 10]]
    type: "intersection"

  - id: G
    boundaries:
      - [[1,3],[3,3]]
      - [[1,1],[3,8]]
      - [[1,3],[8,8]]
      - [[3,3],[3,8]]
    type: "roadway"


  - id: H
    boundaries:
      - [[1, 1], [1, 3]]
      - [[1, 3], [1, 1]]
      - [[3, 3], [1, 3]]
      - [[1, 3], [3, 3]]
    type: "intersection"

  - id: I
    boundaries:
      - [[10,15],[3,3]]
      - [[15,15],[1,3]]
      - [[10,15],[1,1]]
      - [[10,10],[1,3]]
    type: "roadway"

  - id: J
    boundaries:
      - [[15, 15], [1, 3]]
      - [[15, 17], [1, 1]]
      - [[17, 17], [1, 3]]
      - [[15, 17], [3, 3]]
    type: "intersection"

  - id: K
    boundaries:
      - [[15,17],[3,3]]
      - [[15,15],[3,8]]
      - [[15,17],[8,8]]
      - [[17,17],[3,8]]
    type: "roadway"

  - id: L
    boundaries:
      - [[15, 15], [8, 10]]
      - [[15, 17], [8, 8]]
      - [[17, 17], [8, 10]]
      - [[15, 17], [10, 10]]
    type: "intersection"

  - id: M
    boundaries:
      - [[10,15],[10,10]]
      - [[15,15],[8,10]]
      - [[10,15],[8,8]]
      - [[10,10],[8,10]]
    type: "roadway"

  # - id: N
  #   boundaries:
  #     - [[17, 17], [1, 3]]
  #     - [[17, 20], [3, 5]]
  #     - [[20, 22], [5, 5]]
  #     - [[17, 22], [1, 5]]
  #   type: "roadway"

  # - id: O
  #   boundaries:
  #     - [[20, 22], [5, 5]]
  #     - [[20, 20], [5, 7]]
  #     - [[20, 22], [7, 7]]
  #     - [[22, 22], [5, 7]]
  #   type: "intersection"

  # - id: P
  #   boundaries:
  #     - [[17, 17], [8, 10]]
  #     - [[17, 20], [8, 7]]
  #     - [[20, 22], [7, 7]]
  #     - [[17, 22], [10, 7]]
  #   type: "roadway"

  - id: N
    boundaries:
      - [[17, 17], [1, 3]]
      - [[17, 22], [1, 1]]
      - [[22, 22], [1, 3]]
      - [[17, 22], [3, 3]]
    type: "roadway"

  - id: O
    boundaries:
      - [[22, 24], [1, 1]]
      - [[22, 22], [1, 3]]
      - [[22, 24], [3, 3]]
      - [[24, 24], [1, 3]]
    type: "intersection"

  - id: P
    boundaries:
      - [[22, 24], [3, 3]]
      - [[22, 22], [3, 15]]
      - [[22, 24], [15, 15]]
      - [[24, 24], [3, 15]]
    type: "roadway"

  - id: Q
    boundaries:
      - [[22, 24], [15, 15]]
      - [[22, 22], [15, 17]]
      - [[22, 24], [17, 17]]
      - [[24, 24], [15, 17]]
    type: "intersection"

  - id: R
    boundaries:
      - [[10, 10], [15, 17]]
      - [[10, 22], [15, 15]]
      - [[22, 22], [15, 15]]
      - [[10, 22], [17, 17]]
    type: "roadway"

  - id: S
    boundaries:
      - [[8, 8], [15, 17]]
      - [[8, 10], [15, 15]]
      - [[10, 10], [15, 17]]
      - [[8, 10], [17, 17]]
    type: 'intersection'

  - id: T
    boundaries:
      - [[8,10],[10, 10]]
      - [[8,8],[10, 15]]
      - [[8,10],[15,15]]
      - [[10,10],[10,15]]
    type: "roadway"

  - id: U
    boundaries:
      - [[1, 3],[10, 10]]
      - [[1, 1],[10, 25]]
      - [[1, 3],[25, 25]]
      - [[3, 3],[10, 25]]
    type: "roadway"

  - id: V
    boundaries:
      - [[1, 3], [25, 25]]
      - [[1, 1], [25, 27]]
      - [[1, 3], [27, 27]]
      - [[3, 3], [25, 27]]
    type: 'intersection'

  - id: W
    boundaries:
      - [[3,8],[25,25]]
      - [[8,8],[25,27]]
      - [[3,8],[27,27]]
      - [[3,3],[25,27]]
    type: "roadway"

  - id: X
    boundaries:
      - [[8, 10], [25, 25]]
      - [[8, 8], [25, 27]]
      - [[8, 10], [27, 27]]
      - [[10, 10], [25, 27]]
    type: 'intersection'

  - id: Y
    boundaries:
      - [[8,10],[17, 17]]
      - [[8,8],[17, 25]]
      - [[8,10],[25,25]]
      - [[10,10],[17,25]]
    type: "roadway"